apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mealie-pg-role
  namespace: postgres
spec:
  itemPath: "vaults/Kubernetes/items/mealie"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: radarr-pg-role
  namespace: postgres
spec:
  itemPath: "vaults/Kubernetes/items/radarr"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-pg-role
  namespace: postgres
spec:
  itemPath: "vaults/Kubernetes/items/sonarr"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prowlarr-pg-role
  namespace: postgres
spec:
  itemPath: "vaults/Kubernetes/items/prowlarr"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: readarr-pg-role
  namespace: postgres
spec:
  itemPath: "vaults/Kubernetes/items/readarr"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: lidarr-pg-role
  namespace: postgres
spec:
  itemPath: "vaults/Kubernetes/items/lidarr"
