apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-postgres
  namespace: postgres
spec:
  instances: 3

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18

  storage:
    storageClass: local-path
    size: 10Gi

  primaryUpdateMethod: switchover

  managed:
    roles:
      - name: mealie
        ensure: present
        login: true
        passwordSecret:
          name: mealie-pg-role
      - name: radarr
        ensure: present
        login: true
        passwordSecret:
          name: radarr-pg-role
      - name: sonarr
        ensure: present
        login: true
        passwordSecret:
          name: sonarr-pg-role
      - name: prowlarr
        ensure: present
        login: true
        passwordSecret:
          name: prowlarr-pg-role
      - name: readarr
        ensure: present
        login: true
        passwordSecret:
          name: readarr-pg-role
      - name: lidarr
        ensure: present
        login: true
        passwordSecret:
          name: lidarr-pg-role
