apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-postgres
  namespace: postgres
spec:
  instances: 3

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - jetson-nano-kube0

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18

  storage:
    storageClass: local-path
    size: 10Gi

  primaryUpdateMethod: switchover

  enableSuperuserAccess: true

  postgresql:
    pg_hba:
      - host all mealie all trust
      - host all radarr all trust
      - host all sonarr all trust
      - host all prowlarr all trust
      - host all readarr all trust
      - host all lidarr all trust
      - host all pocketid all trust
      - host all outline all trust
      - host all reedme all trust
      - host all n8n all trust
      - host all homebox all trust
      - host all dispatcharr all trust
      - host all backup all trust

  managed:
    roles:
      - name: mealie
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: radarr
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: sonarr
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: prowlarr
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: readarr
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: lidarr
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: pocketid
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: outline
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: reedme
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: n8n
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: homebox
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: dispatcharr
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
      - name: backup
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
