apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-postgres
  namespace: postgres
spec:
  instances: 3

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18

  storage:
    storageClass: local-path
    size: 10Gi

  primaryUpdateMethod: switchover

  postgresql:
    pg_hba:
      - host all mealie all trust
      - host all radarr all trust
      - host all sonarr all trust
      - host all prowlarr all trust
      - host all readarr all trust
      - host all lidarr all trust
      - host all pocketid all trust
      - host all outline all trust
      - host all reedme all trust

  managed:
    roles:
      - name: mealie
        ensure: present
        login: true
      - name: radarr
        ensure: present
        login: true
      - name: sonarr
        ensure: present
        login: true
      - name: prowlarr
        ensure: present
        login: true
      - name: readarr
        ensure: present
        login: true
      - name: lidarr
        ensure: present
        login: true
      - name: pocketid
        ensure: present
        login: true
      - name: outline
        ensure: present
        login: true
      - name: reedme
        ensure: present
        login: true
