apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  namespace: media
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          initContainers:
            - name: render-config
              image: alpine
              command:
                - sh
                - -c
                - apk add --no-cache gettext -q && envsubst < /template/config.template.yml > /rendered/config.yml
              envFrom:
                - secretRef:
                    name: kometa-1pw
              volumeMounts:
                - name: config-template
                  mountPath: /template
                - name: rendered-config
                  mountPath: /rendered
          containers:
            - name: kometa
              image: kometa
              imagePullPolicy: IfNotPresent
              args: [ "--run", "--read-only-config" ]
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: "2000m"
                  memory: 2Gi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: rendered-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: config-template
                  mountPath: /config/custom-collections.yml
                  subPath: custom-collections.yml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: longhorn-kometa-config
            - name: config-template
              configMap:
                name: kometa-config-template
            - name: rendered-config
              emptyDir: {}
          restartPolicy: OnFailure
