apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-kometa-config
  namespace: media
  labels:
    recurring-job-group.longhorn.io/b2-backup: enabled
    # makes Longhorn sync the label above from this PVC to its volume
    recurring-job.longhorn.io/source: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
