apiVersion: homelab.pmcd.io/v1alpha1
kind: HomelabApp
metadata:
  name: homebridge
  namespace: homebridge
spec:
  image: homebridge/homebridge:2026-09-02
  port: 8581
  resources:
    cpuRequest: 25m
    memoryRequest: 128Mi
    cpuLimit: 500m
    memoryLimit: 512Mi
  route:
    hostnames:
    - homebridge.x.pmcd.io
  nodeSelector:
    kubernetes.io/hostname: media-server
  hostNetwork: true
  tolerations:
  - key: dedicated
    operator: Equal
    value: heavy
    effect: NoSchedule
  extraVolumes:
  - name: data
    hostPath: /mnt/usb/homebridge-data
  extraVolumeMounts:
  - name: data
    mountPath: /homebridge
