apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - postgres.yaml
  - httproute.yaml
  - 1password.secret.yaml

images:
  - name: immich-postgres
    newName: ghcr.io/immich-app/postgres
    newTag: "16"
