apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
  namespace: immich
spec:
  selector:
    matchLabels:
      app: immich-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
        - name: postgres
          image: immich-postgres
          env:
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immich-1pw
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-1pw
                  key: DB_PASSWORD
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
spec:
  selector:
    app: immich-postgres
  ports:
    - port: 5432
      targetPort: postgres
