apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: immich
spec:
  instances: 3

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - jetson-nano-kube0

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18

  storage:
    storageClass: local-path
    size: 15Gi

  primaryUpdateMethod: switchover
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
  namespace: immich
spec:
  name: app
  owner: app
  cluster:
    name: postgres
  extensions:
    - name: vector
    - name: earthdistance
    - name: cube
    - name: unaccent
    - name: uuid-ossp
    - name: pg_trgm
