apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-immich-photos
  namespace: immich
spec:
  storageClassName: ""
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: immich-smb-photos-volume-id
    volumeAttributes:
      source: "//192.168.1.253/Photos"
    nodeStageSecretRef:
      name: smb-creds-1pw
      namespace: csi-smb-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: smb-immich-photos
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
