image:
  # renovate: depName=ghcr.io/immich-app/immich-server
  tag: v1.130.0

immich:
  persistence:
    library:
      existingClaim: immich-library

env:
  DB_HOSTNAME: "immich-postgres"
  DB_DATABASE_NAME: "immich"
  REDIS_HOSTNAME: "192.168.1.252"

envFrom:
  - secretRef:
      name: immich-1pw

server:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

machine-learning:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      memory: 4Gi
  persistence:
    cache:
      enabled: true
      size: 10Gi
      storageClass: longhorn
      accessMode: ReadWriteOnce

postgresql:
  enabled: false

redis:
  enabled: false
