controllers:
  main:
    containers:
      main:
        image:
          # renovate: depName=ghcr.io/immich-app/immich-server
          tag: v2.7.5
        env:
          DB_HOSTNAME: "postgres-rw"
          DB_DATABASE_NAME: "app"
          REDIS_HOSTNAME: "192.168.1.252"
        envFrom:
          - secretRef:
              name: immich-1pw

immich:
  persistence:
    library:
      existingClaim: immich-library

server:
  enabled: true
  controllers:
    main:
      containers:
        main:
          probes:
            liveness:
              spec:
                timeoutSeconds: 10
                failureThreshold: 10
            readiness:
              spec:
                timeoutSeconds: 10
                failureThreshold: 10
          resources:
            requests:
              cpu: 100m
              memory: 1500Mi
            limits:
              memory: 4Gi

machine-learning:
  enabled: true
  controllers:
    main:
      containers:
        main:
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              memory: 4Gi
  persistence:
    cache:
      enabled: true
      size: 10Gi
      storageClass: longhorn
      accessMode: ReadWriteOnce
