apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-openwakeword-data
  namespace: voice-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
