apiVersion: v1
kind: Service
metadata:
  name: wyoming-openwakeword
  namespace: voice-assistant
spec:
  type: LoadBalancer
  selector:
    app: wyoming-openwakeword
  ports:
    - name: wyoming
      port: 10400
      targetPort: 10400
      protocol: TCP
