apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-romm-library
spec:
  storageClassName: ""
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: romm-library-volume-id
    volumeAttributes:
      source: "//192.168.1.253/Media/ROMs"
    nodeStageSecretRef:
      name: smb-creds-1pw
      namespace: csi-smb-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-romm-library-claim
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: smb-romm-library
  storageClassName: ""
