apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: cert-manager
    name: in-cluster
  project: core-components
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: cert-manager
      targetRevision: v1.20.3
      repoURL: https://charts.jetstack.io
      helm:
        valuesObject:
          crds:
            enabled: true
          resources:
            requests:
              cpu: 15m
              memory: 105Mi
            limits:
              cpu: 15m
              memory: 106Mi
          cainjector:
            resources:
              requests:
                cpu: 15m
                memory: 121Mi
              limits:
                cpu: 15m
                memory: 122Mi
          webhook:
            resources:
              requests:
                cpu: 15m
                memory: 100Mi
              limits:
                cpu: 15m
                memory: 100Mi
    - path: core/cert-manager
      repoURL: https://github.com/patrickjmcd/k8s-argo.git
      targetRevision: main
