apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: kro-system
    name: in-cluster
  project: core-components
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: kro
      repoURL: oci://registry.k8s.io/kro/charts/kro
      targetRevision: 0.9.4
      helm:
        releaseName: kro
        valuesObject:
          deployment:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 1000m
                memory: 512Mi
