apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-mcp-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: kubernetes-mcp-server
    name: in-cluster
  project: core-components
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: kubernetes-mcp-server
      repoURL: oci://ghcr.io/containers/charts/kubernetes-mcp-server
      targetRevision: 0.1.0
      helm:
        releaseName: kubernetes-mcp-server
        valuesObject:
          ingress:
            enabled: false
          rbac:
            extraClusterRoleBindings:
              - name: kubernetes-mcp-server-admin
                roleRef:
                  name: cluster-admin
                  external: true
    - repoURL: https://github.com/patrickjmcd/k8s-argo.git
      targetRevision: main
      path: apps/kubernetes-mcp-server
