apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  source:
    repoURL: https://github.com/patrickjmcd/k8s-argo.git
    targetRevision: main
    path: core/postgres
  destination:
    namespace: postgres
    name: in-cluster
