apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: prometheus
    name: in-cluster
  project: core-components
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  sources:
    - path: core/prometheus-assets
      repoURL: https://github.com/patrickjmcd/k8s-argo.git
      targetRevision: main
    - repoURL: https://github.com/patrickjmcd/k8s-argo.git
      targetRevision: main
      path: core/grafana-assets
    - chart: kube-prometheus-stack
      targetRevision: 83.4.3
      repoURL: https://prometheus-community.github.io/helm-charts
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          crds:
            updateJob:
              enabled: true
          prometheus:
            prometheusSpec:
              retentionSize: 8GiB
              nodeSelector:
                kubernetes.io/arch: arm64
              startupProbe:
                httpGet:
                  path: /-/healthy
                  port: 9090
                  scheme: HTTP
                failureThreshold: 360
                periodSeconds: 15
                timeoutSeconds: 3
                successThreshold: 1
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
                limits:
                  cpu: 500m
                  memory: 3Gi
              podMonitorSelector: { }
              podMonitorSelectorNilUsesHelmValues: false
              podMonitorNamespaceSelector:
                matchLabels:
                  prometheus: enabled
              serviceMonitorSelector: { }
              serviceMonitorSelectorNilUsesHelmValues: false
              serviceMonitorNamespaceSelector:
                matchLabels:
                  prometheus: enabled
              additionalScrapeConfigs:
                - job_name: pve
                  static_configs:
                    - targets:
                        - 192.168.1.10
                        - 192.168.1.12
                        - 192.168.1.13
                  metrics_path: /pve
                  params:
                    module: [default]
                  relabel_configs:
                    - source_labels: [__address__]
                      target_label: __param_target
                    - source_labels: [__param_target]
                      target_label: instance
                    - target_label: __address__
                      replacement: pve-exporter.prometheus.svc:9221
          prometheusOperator:
            resources:
              requests:
                cpu: 15m
                memory: 100Mi
              limits:
                cpu: 200m
                memory: 256Mi
          alertmanager:
            alertmanagerSpec:
              nodeSelector:
                kubernetes.io/arch: arm64
              resources:
                requests:
                  cpu: 25m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          prometheus-node-exporter:
            affinity: null
            hostNetwork: false
            hostPID: false
            tolerations:
              - effect: NoExecute
                key: node.kubernetes.io/not-ready
                operator: Exists
                tolerationSeconds: 30
              - effect: NoExecute
                key: node.kubernetes.io/unreachable
                operator: Exists
                tolerationSeconds: 30
            resources:
              requests:
                cpu: 25m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 200Mi
          kube-state-metrics:
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
          grafana:
            deploymentStrategy:
              type: Recreate
            tolerations:
              - effect: NoExecute
                key: node.kubernetes.io/not-ready
                operator: Exists
                tolerationSeconds: 30
              - effect: NoExecute
                key: node.kubernetes.io/unreachable
                operator: Exists
                tolerationSeconds: 30
            resources:
              requests:
                cpu: 25m
                memory: 224Mi
              limits:
                cpu: 200m
                memory: 512Mi
            grafana.ini:
              server:
                root_url: https://grafana.x.pmcd.io
            persistence:
              type: pvc
              enabled: true
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              size: 5Gi
