apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: teleport
    name: in-cluster
  project: core-components
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: teleport-kube-agent
      targetRevision: 18.8.0
      repoURL: https://charts.releases.teleport.dev
      helm:
        releaseName: teleport-agent
        valuesObject:
          roles: kube,app,discovery
          proxyAddr: curly-forest.trial.teleport.sh:443
          kubeClusterName: pmcd-cluster
          labels:
            teleport.internal/resource-id: 560ef108-9047-47f3-8fef-ae82b6b31db4
          enterprise: true
          updater:
            enabled: true
            releaseChannel: "stable/cloud"
          highAvailability:
            replicaCount: 2
            podDisruptionBudget:
              enabled: true
              minAvailable: 1
          joinTokenSecret:
            name: teleport-auth-secret
    - path: core/teleport-assets
      repoURL: https://github.com/patrickjmcd/k8s-argo.git
      targetRevision: main
