apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  namespace: prometheus
spec:
  route:
    receiver: n8n-claude
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    matchers:
      - name: alertname
        matchType: "!~"
        value: "^(Watchdog|InfoInhibitor)$"
  receivers:
    - name: n8n-claude
      webhookConfigs:
        - url: http://n8n.default.svc.cluster.local/webhook/alertmanager
          sendResolved: true
