apiVersion: v1
kind: ConfigMap
metadata:
  name: json-exporter-config-tpl
  namespace: prometheus
data:
  config.yml: |
    modules:
      jellyfin:
        headers:
          Authorization: "MediaBrowser Token=${JELLYFIN_TOKEN}"
          Content-Type: application/json
          accept: application/json
        metrics:
        - name: jellyfin
          type: object
          help: User playback metrics from Jellyfin
          path: '{ [?(@.NowPlayingItem)] }'
          labels:
            user_name: '{ .UserName }'
            item_type: '{ .NowPlayingItem.Type }'
            item_name: '{ .NowPlayingItem.Name }'
            item_path: '{ .NowPlayingItem.Path }'
            series_name: '{ .NowPlayingItem.SeriesName }'
            episode_index: '{ .NowPlayingItem.IndexNumber }'
            season_index: '{ .NowPlayingItem.ParentIndexNumber }'
            client_name: '{ .Client }'
            device_name: '{ .DeviceName }'
            session_id: '{ .Id }'
          values:
            is_paused: '{ .PlayState.IsPaused }'
