apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-usb
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-usb
  local:
    path: /mnt/usb/prometheus-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - media-server
