apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - 1password.yaml
  - storage.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - bootstrap-job.yaml
configMapGenerator:
  - name: garage-bootstrap
    namespace: garage
    files:
      - bootstrap.py
generatorOptions:
  disableNameSuffixHash: true
