apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-outline
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: ''
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: media-smb-outline-volume-id
    volumeAttributes:
      source: //192.168.1.253/AppConfig/outline
    nodeStageSecretRef:
      name: smb-creds-1pw
      namespace: csi-smb-provisioner
