apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-outline-claim
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: smb-outline
  storageClassName: ''
