image:
  repository: outlinewiki/outline
  tag: "1.6.1"

service:
  port: 80
  containerPort: 3000

resources:
  requests:
    cpu: 25m
    memory: 400Mi
  limits:
    cpu: 1000m
    memory: 800Mi

probes:
  readiness:
    type: tcpSocket
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
  liveness:
    enabled: true
    type: tcpSocket
    initialDelaySeconds: 180
    failureThreshold: 5
    periodSeconds: 10
    timeoutSeconds: 10
  startup:
    enabled: true
    type: tcpSocket
    failureThreshold: 30
    periodSeconds: 5

httproute:
  enabled: true
  hostnames:
    - outline.x.pmcd.io

persistence:
  enabled: true
  type: smb
  size: 500Mi
  mountPath: /var/lib/outline/data
  accessMode: ReadWriteMany
  smb:
    source: "//192.168.1.253/AppConfig/outline"
    volumeHandle: media-smb-outline-volume-id

onePassword:
  enabled: true
  itemPath: "vaults/Kubernetes/items/outline"

env:
  TZ: America/Chicago
  FILE_STORAGE: local
  FILE_STORAGE_UPLOAD_MAX_SIZE: '26214400'

envFrom:
  - secretRef:
      name: outline-1pw
