apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - certificate.yaml
  - configmap-cert-sync.yaml
  - deployment.yaml
  - loadbalancer-service.yaml
