apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
  namespace: voice-assistant
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.8.201
  selector:
    app: wyoming-whisper
  ports:
    - name: wyoming
      port: 10300
      targetPort: 10300
      protocol: TCP
