apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml
  - httproute.yaml

images:
  - name: bazarr
    newName: linuxserver/bazarr
    newTag: 1.5.1
