apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terminus-uploads
  namespace: terminus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
