apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - configmap-local-dns.yaml
  - service-dns-tcp.yaml
  - service-dns-udp.yaml
  - service-web.yaml
  - httproute.yaml
  - storage.yaml
  - 1password.secret.yaml
