apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.8.204"
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  externalTrafficPolicy: Local
