apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  labels:
    recurring-job-group.longhorn.io/b2-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
