apiVersion: homelab.pmcd.io/v1alpha1
kind: HomelabApp
metadata:
  name: sparkyfitness
  namespace: sparkyfitness
spec:
  image: codewithcj/sparkyfitness:v1.7.3
  port: 80
  resources:
    cpuRequest: 10m
    memoryRequest: 32Mi
    cpuLimit: 500m
    memoryLimit: 128Mi
  probes:
    type: httpGet
    readiness:
      initialDelaySeconds: 5
      timeoutSeconds: 3
    liveness:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
  route:
    hostnames:
    - sparkyfitness.x.pmcd.io
  env:
    TZ: America/Chicago
    SPARKY_FITNESS_SERVER_HOST: sparkyfitness-server
    SPARKY_FITNESS_SERVER_PORT: '3010'
    SPARKY_FITNESS_FRONTEND_URL: https://sparkyfitness.x.pmcd.io
  glance:
    monitor: true
    title: SparkyFitness
