apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
  - service-monitor.yaml
  - 1password.secret.yaml
  - backup-target.yaml
  - longhorn-node-pi4-kube0.yaml
  - longhorn-node-pi4-kube1.yaml
  - longhorn-node-kube-worker-1.yaml
  - longhorn-node-kube-leader.yaml
  - longhorn-node-kube-leader-2.yaml
  - longhorn-node-pi5-kube0.yaml
  - longhorn-node-pi5-kube1.yaml
  - longhorn-node-pi5-kube2.yaml
  - longhorn-node-jetson-nano-kube0.yaml
  - recurring-jobs.yaml
  - settings.yaml


