apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - httproute.yaml
  - service.yaml
  - storage.yaml
  - 1password.secret.yaml
  - 1password.config.yaml



images:
  - name: frigate
    newName:  ghcr.io/blakeblackshear/frigate
    newTag: stable