apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - whisper/pvc.yaml
  - whisper/deployment.yaml
  - whisper/service.yaml
  - piper/pvc.yaml
  - piper/deployment.yaml
  - piper/service.yaml
  - openwakeword/pvc.yaml
  - openwakeword/deployment.yaml
  - openwakeword/service.yaml
