apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-ia-ignition-config
  labels:
    recurring-job-group.longhorn.io/b2-backup: enabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi