image:
  repository: ghcr.io/frederikemmer/medialyze
  tag: "0.2.3"

service:
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

httproute:
  enabled: true
  hostnames:
    - medialyze.x.pmcd.io

persistence:
  enabled: true
  type: longhorn
  size: 2Gi
  mountPath: /config

env:
  TZ: America/Chicago
  SCAN_RUNTIME_WORKER_COUNT: "4"

extraVolumes:
  - name: media
    persistentVolumeClaim:
      claimName: smb-media-claim

extraVolumeMounts:
  - mountPath: /media
    name: media
    readOnly: true
