apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-runtime-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: apps/nvidia-runtime-config
    repoURL: https://github.com/patrickjmcd/k8s-argo.git
    targetRevision: main
