apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terminus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: terminus
    name: in-cluster
  project: apps
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
  source:
    path: apps/terminus
    repoURL: https://github.com/patrickjmcd/k8s-argo.git
    targetRevision: main
