apiVersion: homelab.pmcd.io/v1alpha1
kind: HomelabApp
metadata:
  name: iss-in-space
  namespace: default
spec:
  image: ghcr.io/patrickjmcd/iss-in.space:v1.10.0
  port: 4321
  resources:
    cpuRequest: 25m
    memoryRequest: 128Mi
    cpuLimit: 200m
    memoryLimit: 256Mi
  route:
    hostnames:
    - iss.x.pmcd.io
    publicHostnames:
    - iss-in.space
  imagePullSecrets:
  - ghcr-registry-cred
