apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - loadbalancer-service.yaml
  - bedrockconnect.yaml
configMapGenerator:
  - name: bedrockconnect-servers
    files:
      - custom_servers.json
