apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-sparkyfitness-server-data
  namespace: sparkyfitness
  labels:
    recurring-job-group.longhorn.io/b2-backup: enabled
    recurring-job.longhorn.io/source: enabled
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
