apiVersion: v1
kind: Service
metadata:
  name: hivemq
  namespace: hivemq
spec:
  selector:
    app.kubernetes.io/name: hivemq
    app.kubernetes.io/instance: hivemq
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: control-center
      port: 8080
      targetPort: control-center
      protocol: TCP
